"""empty message

Revision ID: 104c63a8f6f4
Revises: 0cad1043775e
Create Date: 2024-04-28 16:37:03.195580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104c63a8f6f4'
down_revision = '0cad1043775e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('available_dates')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_dates', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
