"""empty message

Revision ID: 303e1269b9c4
Revises: 104c63a8f6f4
Create Date: 2024-04-28 17:04:54.452950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303e1269b9c4'
down_revision = '104c63a8f6f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_available_dates', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('_available_dates')

    # ### end Alembic commands ###
